### ISSUE TITLE
Allow the use of locally stored images

### ISSUE THREAD

**Issue by rGunti** [jparkerweb/pexels-banner#2]
The plugin looks really nice but I'd like to use my own images as banners. Would it be possible to link to an image stored in my vault (or any other URL)?

**Comment by jparkerweb** [comment]
The plugin already supports image URLs ([usage guide](https://github.com/jparkerweb/pexels-banner?tab=readme-ov-file#usage)).
I will look into using images that already exist in the vault (thanks for the idea).

**Comment by jparkerweb** [comment]
@rGunti I just updated the plugin with support for local image in the vault.
see the readme for updated docs, but it will support both a full local path relative to the file in your vault, as well as obsidian internal link format!

**Comment by MaximilianMauroner** [comment]
> support both a full local path relative to the file in your vault, as well as obsidian internal link format!

@jparkerweb   
Just to clarify—if I have a file at `/path/to/the/folder/attachments/name_of_file.png` and my vault root is `/path/to/the/folder`,  

should I be able to reference it as `attachments/name_of_file.png` or do I always need the full path `/path/to/the/folder/attachments/name_of_file.png`?  

I was trying this out with the new **bases** feature, but it doesn’t seem to work for me. Maybe I’m misunderstanding how the relative pathing is supposed to be configured in the plugin. Could you confirm what the expected behavior is?
